### ISSUE TITLE
Single Notícias >> Navegação

### ISSUE THREAD

**Issue by diegorojas** [brasadesign/wp-polis#35]
Colocar uma navegação "Anterior" / "Próximo" na parte inferior dos single posts. No lugar padrão, antes dos comentários:

![local-nav](https://cloud.githubusercontent.com/assets/3632627/10743374/cd2a9aa0-7c19-11e5-9504-5d572d93b019.png)

**Comment by matheusgimenez** [comment]
feito no ultimo commit
